name: CI

on: [push, pull_request]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Sonarless Scan
        uses: actions/gitricko/sonar-less-action@main
