name: CI

on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: list all actions
        run: |
          ls -lahd /home/runner/work/_actions/*

      - name: Sonarless Scan
        uses: gitricko/sonar-less-action@fix/action-on-other-repo
