name: Sonarless-Scan

on: [push, pull_request]

jobs:
  Sonarless-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sonarless Scan
        uses: gitricko/sonarless@v0
